name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: "$GITHUB_WORKSPACE/VolunTrackerUI"

      - name: Build project
        run: npm run build
        working-directory: "$GITHUB_WORKSPACE/VolunTrackerUI"

#      - name: Upload production-ready build files
#        uses: actions/upload-artifact@v3
#        with:
#          name: production-files
#          path: $GITHUB_WORKSPACE/voluntrackerui/dist

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_BAY_0F396BC10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/VolunTrackerUI" # App source code path
          output_location: "dist" # Built app content directory - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
